import { Overpass_Mono } from 'next/font/google'
import SiteHeader from '@/components/SiteHeader';
import "./globals.css";
import { AuthProvider } from "./context/context";
import Footer from '@/components/Footer';

const overpass_mono = Overpass_Mono({
  weight: '400',
  subsets: ['latin'],
})
 
export const metadata = {
  title: "BrandKicks",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={overpass_mono.className}
      >
        <AuthProvider>
          <SiteHeader/>
          {children}
        </AuthProvider>
        <Footer/>
      </body>
    </html>
  );
}
